name: 'Deploy Application/Service'
description: 'Deploy Sample Book App service via pm2'
inputs:
  environment:
    description: 'Environment where to deploy Sample Book App'
    required: true
  port:
    required: true
runs:
  using: composite
  steps:
    - run: echo "Deployment to ${{ inputs.environment }} environment has started.."
      shell: cmd
    - name: Install dependecies
      run: npm install
      shell: cmd
    - name: Cleanup of old running service
      run: node_modules\.bin\pm2 delete books-${{ inputs.environment }} || exit 0
      shell: cmd
    - name: Rnning service
      run: node_modules\.bin\pm2 start -n books-${{ inputs.environment }} index.js -- -- ${{ inputs.port }}
      shell: cmd
    - run: echo "Deployment to ${{ inputs.environment }} environment finished.."
      shell: cmd

      # node_modules\.bin\pm2 delete "books-STG" || exit 0