# This is a basic workflow to help you get started with Actions

name: Sample Book App Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-install-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies"
      - name: Install all dependencies
        run: npm install
      - name: Print step name
        run: echo "Dependencies installed"
  deploy-dev:
    runs-on: self-hosted
    needs: build-install-deps
    steps:
      - uses: actions/checkout@v6
      - run: echo "Deployment to DEV has started.."
      - name: echo "Install dependencies"
        run: npm install
      - name: Cleanup of running service
        shell: cmd
        run: node_modules\.bin\pm2 delete "books-DEV" || exit 0
      - name: Running service
        run: node_modules\.bin\pm2 start -n "books-DEV" index.js -- -- 1010
      - run: echo "Deployment to DEV finished"
  test-dev:
    runs-on: self-hosted
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing book service has started on DEV.."
  deploy-stg:
    runs-on: self-hosted
    needs: test-dev
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to STG has started.."
  test-stg:
    runs-on: self-hosted
    needs: deploy-stg
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing book service has started on STG.."
  deploy-prod:
    runs-on: self-hosted
    needs: test-stg
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to PROD has started.."
  test-prod:
    runs-on: self-hosted
    needs: deploy-prod
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing book service has started on PROD.."