# This is a basic workflow to help you get started with Actions

name: Sample Book App Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-install-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies"
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to DEV has started.."
  test-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing book service has started on DEV.."
  deploy-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to STG has started.."
  test-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing book service has started on STG.."
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to PROD has started.."
  test-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Testing book service has started on PROD.."